defaults: &defaults
  working_directory: ~/repo
  docker:
      - image: circleci/node:latest

version: 2

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v1-code-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  setup:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-setup-{{ checksum "yarn.lock" }}
      - run: yarn -v && node -v
      - run: yarn install
      - save_cache:
          key: v1-setup-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-setup-{{ checksum "yarn.lock" }}
      - run: yarn run build

  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-setup-{{ checksum "yarn.lock" }}
      - run: yarn test

  deploy-production:
    <<: *defaults
    environment:
        - APP_NAME: taringa
    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - "fa:37:01:71:aa:80:92:16:9d:f5:69:a6:7a:90:8b:3b"
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy on production
          command: git push heroku $CIRCLE_SHA1:refs/heads/master

  deploy-staging:
    <<: *defaults
    environment:
        - APP_NAME: taringa-staging
    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - "fa:37:01:71:aa:80:92:16:9d:f5:69:a6:7a:90:8b:3b"
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy on staging
          command: git push heroku $CIRCLE_SHA1:refs/heads/master

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - setup:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - deploy-staging:
          requires:
            - build
            - test
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   only: master
      - deploy-production:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
